<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="servicebot">

	<xacro:macro name="depth_camera" params="name parent *origin">
		<xacro:property name="depth_camera" value="0.05" />
		<joint name="${name}_joint" type="fixed">
			<axis xyz="0 1 0" />
			<xacro:insert_block name="origin" />
			<parent link="${parent}" />
			<child link="${name}_link" />
		</joint>

		<joint name="${name}_optical_joint" type="fixed">
			<origin xyz="0 0.015 0" rpy="${-pi/2} 0 ${-pi/2}" />
			<parent link="${name}_link" />
			<child link="${name}_link_optical" />
		</joint>

		<joint name="${name}_gazebo_joint" type="fixed">
			<origin xyz="0 0.015 0" rpy="0 0 0" />
			<parent link="${name}_link" />
			<child link="${name}_link_depth" />
		</joint>

		<link name="${name}_link">
			<collision>
				<origin xyz="0 0.02 0" rpy="${M_PI_2} 0 ${M_PI_2}" />
				<geometry>
					<box size="${depth_camera} ${depth_camera} ${2*depth_camera}" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0.02 0" rpy="${M_PI_2} 0 ${M_PI_2}" />
				<geometry>
					<mesh filename="package://service_description/meshes/sensors/d435.dae" />
				</geometry>
				<material name="red">
					<color rgba="1 0 0 1" />
				</material>
			</visual>

		</link>

		<link name="${name}_link_optical"></link>

		<link name="${name}_link_depth" />

	</xacro:macro>
</robot>